title: CrackMiDrAiDocs
lang: cn
description: A public document for CrackMiDrAi

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock